-- Create Menu Table
create table public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text,
  is_visible boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  total_price numeric not null,
  status text default 'pending', -- 'pending', 'paid', 'completed', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  menu_id bigint references public.menu(id) on delete set null,
  name text not null, -- Snapshot of name in case menu changes
  price numeric not null, -- Snapshot of price
  quantity integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, depending on your auth policy, here we keep it simple for now or enable public read)
alter table public.menu enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Policies (Example: Public read for menu, authenticated/public write for orders)
create policy "Enable read access for all users" on public.menu for select using (true);
create policy "Enable insert for authenticated users only" on public.menu for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.menu for update using (auth.role() = 'authenticated');

create policy "Enable insert for all users" on public.orders for insert with check (true);
create policy "Enable select for authenticated users" on public.orders for select using (auth.role() = 'authenticated');

create policy "Enable insert for all users" on public.order_items for insert with check (true);
create policy "Enable select for authenticated users" on public.order_items for select using (auth.role() = 'authenticated');

-- STORAGE SETUP
-- Create the storage bucket for menu images
insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do nothing;

-- Set up security policies for the storage bucket
-- 1. Allow public access to view images
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'menu-images' );

-- 2. Allow authenticated users to upload images
create policy "Authenticated Upload"
  on storage.objects for insert
  with check ( bucket_id = 'menu-images' and auth.role() = 'authenticated' );

-- 3. Allow authenticated users to update/delete their images (optional, good to have)
create policy "Authenticated Update"
  on storage.objects for update
  using ( bucket_id = 'menu-images' and auth.role() = 'authenticated' );

create policy "Authenticated Delete"
  on storage.objects for delete
  using ( bucket_id = 'menu-images' and auth.role() = 'authenticated' );
